Doc/issue11
Control-Cash/controlcash pull request #45
Opened 2023-04-29 23:41 UTC by biancamdros

2023-04-30 00:19 UTC, br-adriel requested changes

2023-04-30 00:19 UTC, br-adriel commented on docs/user-stories.md
> +Descrição: O sistema deve permitir o registro de  vendas. Manter vendas contém os seguintes atributos: data, hora, cliente, itens de venda, valor total, pagamento e status.
Faltou dizer que o permite a listagem e a visualização das vendas também

2023-04-30 00:19 UTC, br-adriel commented on docs/user-stories.md
> +Descrição: O sistema deve permitir o registro de  vendas. Manter vendas contém os seguintes atributos: data, hora, cliente, itens de venda, valor total, pagamento e status.
Ao invés de "Manter vendas contém...." pode ser só "A entidade venda contém..." ou "Uma venda contém..."

2023-04-30 00:19 UTC, br-adriel commented on docs/user-stories.md
> +| TA03.05                  |Teste de relatórios: ao gerar um relatório de vendas em um determinado período de tempo, o sistema deve exibir todas as vendas realizadas nesse período, incluindo informaç
Acho que o teste TA03.05 faz mais sentido estar em um caso de uso "gerar relatório de venda" ou algo do tipo, manter normalmente inclui só o criar/ver/editar/excluir.

2023-05-02 17:15 UTC, biancamdros commented
Fiz o commit, mas referenciei errado, deveria ser #11 e coloquei #35.

2023-05-02 18:11 UTC, br-adriel commented
Mas foi nesse branch? Porque era pra tá aparecendo na área de arquivos alterados, e não está. Verifique se vc modificou nesse branch ou se foi no outro

2023-05-12 01:02 UTC, closed without merging